Repository infinum/android-handbook, pull requests merged in 2020-04, with the labels that each got.

#58 Remove deprecated, unmaintained and archived libraries
  Useful tools & utilities/Libraries.md
Labels: content update

#59 Fix broken links
  Building quality apps/Naming.md
  Building quality apps/Testing.md
  Building quality apps/Using Git.md
  Common Android/Room migrations.md
  Deployment/Play Store.md
  Deployment/Release practices.md
  Project structure/Gradle build system.md
  Project structure/MVP.md
  Project structure/Project architecture.md
  Project structure/Project setup.md
Labels: bug

#60 Updated styles readme with TextView vs Button
  Common Android/View styles.md
Labels: help wanted
